services:
  # Install oracle and set up the  database.
  oracle:
    container_name: dbz_oracle19
    image: oracle/database:19.3.0-ee
    ports:
      - "1521:1521"
      - "5500:5500"
      - "2484:2484"
    restart: always
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=oraclepw
      - ORACLE_EDITION=enterprise
      - ORACLE_CHARACTERSET=AL32UTF8
      - ENABLE_ARCHIVELOG=true
      - ENABLE_FORCE_LOGGING=false
      - ENABLE_TCPS=false
    volumes:
      - ./data:/opt/oracle/oradata
      - ./src/main/resources/scripts:/home/oracle/scripts

  # Install Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
