--## Referring to: https://debezium.io/blog/2022/09/30/debezium-oracle-series-part-1/
--## Configure Oracle: Archive logs
ALTER SYSTEM SET db_recovery_file_dest_size = 10G;
ALTER SYSTEM SET db_recovery_file_dest = '/opt/oracle/oradata/ORCLCDB' scope=spfile;

SHUTDOWN IMMEDIATE;
STARTUP MOUNT;

ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
ARCHIVE LOG LIST;


--## Configure Oracle: Redo logs
SELECT GROUP#, BYTES/1024/1024 SIZE_MB, STATUS FROM V$LOG ORDER BY 1;
SELECT GROUP#, MEMBER FROM V$LOGFILE ORDER BY 1, 2;

DECLARE
    LOG_STATUS VARCHAR2(16);
BEGIN
    SELECT STATUS INTO LOG_STATUS FROM V$LOG WHERE GROUP# = 1;
    IF LOG_STATUS = 'CURRENT' THEN
        EXECUTE IMMEDIATE 'ALTER SYSTEM SWITCH LOGFILE';
        LOOP
            SELECT STATUS INTO LOG_STATUS FROM V$LOG WHERE GROUP# = 1;
            EXIT WHEN LOG_STATUS != 'ACTIVE';
            DBMS_SESSION.SLEEP(60);
        END LOOP;
    END IF;
    EXECUTE IMMEDIATE 'ALTER DATABASE CLEAR LOGFILE GROUP 1';
    EXECUTE IMMEDIATE 'ALTER DATABASE DROP LOGFILE GROUP 1';
    EXECUTE IMMEDIATE 'ALTER DATABASE ADD LOGFILE GROUP 1 (''/opt/oracle/oradata/ORCLCDB/redo01.log'') size 500M REUSE';

    SELECT STATUS INTO LOG_STATUS FROM V$LOG WHERE GROUP# = 2;
    IF LOG_STATUS = 'CURRENT' THEN
        EXECUTE IMMEDIATE 'ALTER SYSTEM SWITCH LOGFILE';
        LOOP
            SELECT STATUS INTO LOG_STATUS FROM V$LOG WHERE GROUP# = 2;
            EXIT WHEN LOG_STATUS != 'ACTIVE';
            DBMS_SESSION.SLEEP(60);
        END LOOP;
    END IF;
    EXECUTE IMMEDIATE 'ALTER DATABASE CLEAR LOGFILE GROUP 2';
    EXECUTE IMMEDIATE 'ALTER DATABASE DROP LOGFILE GROUP 2';
    EXECUTE IMMEDIATE 'ALTER DATABASE ADD LOGFILE GROUP 2 (''/opt/oracle/oradata/ORCLCDB/redo02.log'') size 500M REUSE';

    SELECT STATUS INTO LOG_STATUS FROM V$LOG WHERE GROUP# = 3;
    IF LOG_STATUS = 'CURRENT' THEN
        EXECUTE IMMEDIATE 'ALTER SYSTEM SWITCH LOGFILE';
        LOOP
            SELECT STATUS INTO LOG_STATUS FROM V$LOG WHERE GROUP# = 3;
            EXIT WHEN LOG_STATUS != 'ACTIVE';
            DBMS_SESSION.SLEEP(60);
        END LOOP;
    END IF;
    EXECUTE IMMEDIATE 'ALTER DATABASE CLEAR LOGFILE GROUP 3';
    EXECUTE IMMEDIATE 'ALTER DATABASE DROP LOGFILE GROUP 3';
    EXECUTE IMMEDIATE 'ALTER DATABASE ADD LOGFILE GROUP 3 (''/opt/oracle/oradata/ORCLCDB/redo03.log'') size 500M REUSE';

END;
/
COMMIT;

SELECT GROUP#, BYTES/1024/1024 SIZE_MB, STATUS FROM V$LOG ORDER BY 1;


--## Configure Oracle: Supplemental Logging
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;


--## Configure Oracle: User setup
CONNECT sys/oraclepw@ORCLCDB as sysdba;
CREATE TABLESPACE logminer_tbs DATAFILE '/opt/oracle/oradata/ORCLCDB/logminer_tbs.dbf' SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;

CONNECT sys/oraclepw@ORCLPDB1 as sysdba;
CREATE TABLESPACE logminer_tbs DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/logminer_tbs.dbf' SIZE 25M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;

CONNECT sys/oraclepw@ORCLCDB as sysdba;
CREATE USER c##dbzuser IDENTIFIED BY dbzpswd DEFAULT TABLESPACE LOGMINER_TBS QUOTA UNLIMITED ON LOGMINER_TBS CONTAINER=ALL;

GRANT CREATE SESSION TO c##dbzuser CONTAINER=ALL;
GRANT SET CONTAINER TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$DATABASE TO c##dbzuser CONTAINER=ALL;
GRANT FLASHBACK ANY TABLE TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ANY TABLE TO c##dbzuser CONTAINER=ALL;
GRANT SELECT_CATALOG_ROLE TO c##dbzuser CONTAINER=ALL;
GRANT EXECUTE_CATALOG_ROLE TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ANY TRANSACTION TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ANY DICTIONARY TO c##dbzuser CONTAINER=ALL;
GRANT LOGMINING TO c##dbzuser CONTAINER=ALL;

GRANT CREATE TABLE TO c##dbzuser CONTAINER=ALL;
GRANT LOCK ANY TABLE TO c##dbzuser CONTAINER=ALL;
GRANT CREATE SEQUENCE TO c##dbzuser CONTAINER=ALL;

GRANT EXECUTE ON DBMS_LOGMNR TO c##dbzuser CONTAINER=ALL;
GRANT EXECUTE ON DBMS_LOGMNR_D TO c##dbzuser CONTAINER=ALL;

GRANT SELECT ON V_$LOG TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$LOG_HISTORY TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_LOGS TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_CONTENTS TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$LOGMNR_PARAMETERS TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$LOGFILE TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVED_LOG TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO c##dbzuser CONTAINER=ALL;
GRANT SELECT ON V_$TRANSACTION TO c##dbzuser CONTAINER=ALL;

EXIT;

